# Generated by Django 5.2.3 on 2025-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
