# Generated by Django 5.2.3 on 2025-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_cart_is_active_alter_shippingaddress_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="store.product", verbose_name="orders"),
        ),
    ]
