# Generated by Django 5.2.3 on 2025-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_order_product_remove_order_quantity_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={},
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="product price "
            ),
        ),
    ]
