# Generated by Django 5.2.3 on 2025-07-14 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_shippingaddress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.order",
            ),
        ),
    ]
