# Generated by Django 5.2.3 on 2025-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_shippingaddress_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
