# Generated by Django 5.2.3 on 2025-07-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_order_shipped_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_fa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True, verbose_name="product  description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_fa",
            field=models.TextField(null=True, verbose_name="product  description"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                max_length=50, null=True, verbose_name="product name"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_fa",
            field=models.CharField(
                max_length=50, null=True, verbose_name="product name"
            ),
        ),
    ]
